name: Movie Collector
on:
  schedule:
    - cron: '0 0 * * *' # Every night
  workflow_dispatch:
jobs:
  - name: Install dependencies
        run: |
          pip install requests wikipedia-api

      - name: Run Script
        run: |
          python scripts/collector.py
